# Generated by Django 4.2.30 on 2026-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
